### ISSUE TITLE
Potential dockerfile build-time speedup

### ISSUE THREAD

**Issue by s7726** [FredTingaud/quick-bench-docker#1]
https://github.com/FredTingaud/quick-bench-docker/blob/fe31fba2fc42be81ecccf76aa6e1089aa7840ac4/Dockerfile#L25-L28

Maybe move to something like:
```
git clone --branch v4.9 --depth 1 https://github.com/torvalds/linux.git
cd linux/tools/perf
```
https://stackoverflow.com/questions/8932389/git-shallow-clone-to-specific-tag

To avoid pulling the entire history of the Linux kernel.

Possibly with something like this:
https://stackoverflow.com/a/52269934/1006048

To avoid pulling unnecessary portions of the repo, although that could get weird with all of the inter-dependencies.

**Comment by FredTingaud** [comment]
That's a very good idea! Thanks!
